export enum KeyCodes {
	LEFT_ARROW_KEY = 'ARROWLEFT',
	RIGHT_ARROW_KEY = 'ARROWRIGHT',
	UP_ARROW_KEY = 'ARROWUP',
	DOWN_ARROW_KEY = 'ARROWDOWN',
	DELETE_KEY = 'BACKSPACE',
	SPACEBAR_KEY = 'SPACE',
	TAB_KEY = 'TAB'
}
