// Mock cellMap for db
// Removes data about hasFocus
// Adds data about across and down word start/end locations
export default {
	'0:0': {
		id: '0:0',
		displayNumber: 1,
		correctValue: 'Q',
		value: '',
		x: 0,
		y: 0,
		index: 0,
		isSymmetrical: true,
		acrossWordStartX: 0,
		acrossWordEndX: 4,
		downWordStartY: 0,
		downWordEndY: 4
	},
	'1:0': {
		id: '1:0',
		displayNumber: 0,
		correctValue: 'U',
		value: '',
		x: 1,
		y: 0,
		index: 1,
		isSymmetrical: true,
		acrossWordStartX: 0,
		acrossWordEndX: 4
	},
	'2:0': {
		id: '2:0',
		displayNumber: 0,
		correctValue: 'I',
		value: '',
		x: 2,
		y: 0,
		index: 2,
		isSymmetrical: true,
		acrossWordStartX: 0,
		acrossWordEndX: 4
	},
	'3:0': {
		id: '3:0',
		displayNumber: 0,
		correctValue: 'N',
		value: '',
		x: 3,
		y: 0,
		index: 3,
		isSymmetrical: true,
		acrossWordStartX: 0,
		acrossWordEndX: 4
	},
	'4:0': {
		id: '4:0',
		displayNumber: 2,
		correctValue: 'T',
		value: '',
		x: 4,
		y: 0,
		index: 4,
		isSymmetrical: true,
		acrossWordStartX: 0,
		acrossWordEndX: 4,
		downWordStartY: 0,
		downWordEndY: 2
	},
	'0:1': {
		id: '0:1',
		displayNumber: 0,
		correctValue: 'U',
		value: '',
		x: 0,
		y: 1,
		index: 5,
		isSymmetrical: true,
		downWordStartY: 0,
		downWordEndY: 4
	},
	'1:1': {
		id: '1:1',
		displayNumber: 0,
		correctValue: '',
		value: '',
		x: 1,
		y: 1,
		index: 6,
		isSymmetrical: false
	},
	'2:1': {
		id: '2:1',
		displayNumber: 0,
		correctValue: '',
		value: '',
		x: 2,
		y: 1,
		index: 7,
		isSymmetrical: true
	},
	'3:1': {
		id: '3:1',
		displayNumber: 0,
		correctValue: '',
		value: '',
		x: 3,
		y: 1,
		index: 8,
		isSymmetrical: false
	},
	'4:1': {
		id: '4:1',
		displayNumber: 0,
		correctValue: 'A',
		value: '',
		x: 4,
		y: 1,
		index: 9,
		isSymmetrical: true,
		downWordStartY: 0,
		downWordEndY: 2
	},
	'0:2': {
		id: '0:2',
		displayNumber: 0,
		correctValue: 'I',
		value: '',
		x: 0,
		y: 2,
		index: 10,
		isSymmetrical: true,
		downWordStartY: 0,
		downWordEndY: 4
	},
	'1:2': {
		id: '1:2',
		displayNumber: 0,
		correctValue: '',
		value: '',
		x: 1,
		y: 2,
		index: 11,
		isSymmetrical: true
	},
	'2:2': {
		id: '2:2',
		displayNumber: 3,
		correctValue: 'P',
		value: '',
		x: 2,
		y: 2,
		index: 12,
		isSymmetrical: true,
		acrossWordStartX: 2,
		acrossWordEndX: 4,
		downWordStartY: 2,
		downWordEndY: 4
	},
	'3:2': {
		id: '3:2',
		displayNumber: 0,
		correctValue: 'O',
		value: '',
		x: 3,
		y: 2,
		index: 13,
		isSymmetrical: true,
		acrossWordStartX: 2,
		acrossWordEndX: 4
	},
	'4:2': {
		id: '4:2',
		displayNumber: 0,
		correctValue: 'T',
		value: '',
		x: 4,
		y: 2,
		index: 14,
		isSymmetrical: true,
		downWordStartY: 0,
		downWordEndY: 2,
		acrossWordStartX: 2,
		acrossWordEndX: 4
	},
	'0:3': {
		id: '0:3',
		displayNumber: 0,
		correctValue: 'L',
		value: '',
		x: 0,
		y: 3,
		index: 15,
		isSymmetrical: true,
		downWordStartY: 0,
		downWordEndY: 4
	},
	'1:3': {
		id: '1:3',
		displayNumber: 0,
		correctValue: '',
		value: '',
		x: 1,
		y: 3,
		index: 16,
		isSymmetrical: false
	},
	'2:3': {
		id: '2:3',
		displayNumber: 0,
		correctValue: 'I',
		value: '',
		x: 2,
		y: 3,
		index: 17,
		isSymmetrical: true,
		downWordStartY: 2,
		downWordEndY: 4
	},
	'3:3': {
		id: '3:3',
		displayNumber: 0,
		correctValue: '',
		value: '',
		x: 3,
		y: 3,
		index: 18,
		isSymmetrical: false
	},
	'4:3': {
		id: '4:3',
		displayNumber: 0,
		correctValue: '',
		value: '',
		x: 4,
		y: 3,
		index: 19,
		isSymmetrical: true
	},
	'0:4': {
		id: '0:4',
		displayNumber: 0,
		correctValue: 'L',
		value: '',
		x: 0,
		y: 4,
		index: 20,
		isSymmetrical: true,
		downWordStartY: 0,
		downWordEndY: 4
	},
	'1:4': {
		id: '1:4',
		displayNumber: 0,
		correctValue: '',
		value: '',
		x: 1,
		y: 4,
		index: 21,
		isSymmetrical: true
	},
	'2:4': {
		id: '2:4',
		displayNumber: 0,
		correctValue: 'N',
		value: '',
		x: 2,
		y: 4,
		index: 22,
		isSymmetrical: true,
		downWordStartY: 2,
		downWordEndY: 4
	},
	'3:4': {
		id: '3:4',
		displayNumber: 0,
		correctValue: '',
		value: '',
		x: 3,
		y: 4,
		index: 23,
		isSymmetrical: true
	},
	'4:4': {
		id: '4:4',
		displayNumber: 0,
		correctValue: '',
		value: '',
		x: 4,
		y: 4,
		index: 24,
		isSymmetrical: true
	}
};
