name: Playwright Tests
env:
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
on:
  push:
    branches:
      - main
jobs:
  run-e2es:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
